In [1]:
# Import libraries necessary for this project
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#load data
df = pd.read_csv('../cleaned_data.csv')

In [3]:
df.head()


Case Identification  Region  Type of Place of Residence  \
0                 1002       2                           1   
1                 1004       2                           1   
2                 1007       2                           1   
3                 1010       2                           1   
4                 1013       2                           1   

   Source of Drinking Water  Type of Toilet Facility  Has Electricity  \
0                         7                       12                1   
1                        12                       12                1   
2                        13                       12                1   
3                        13                       12                1   
4                        12                       12                1   

   Main Floor Material  Main Wall Material  Main Roof Material  Has Bicycle  \
0                    1                   4                  13            0   
1                    5                   4                  13            1   
2                    1                   4                  13            0   
3                    1                   4                  13            1   
4                    2                   4                  13            0   

   Has Motorcycle or Scooter  Has Car or Truck  \
0                          0                 0   
1                          0                 1   
2                          1                 0   
3                          1                 1   
4                          1                 1   

   Has Mosquito Bed Net for Sleeping  Owns Land Suitable for Agriculture  \
0                                  1                                   1   
1                                  1                                   1   
2                                  1                                   0   
3                                  1                                   0   
4                                  1                                   0   

   Has Bank Account  Wealth Index  State  
0                 0             3     33  
1                 1             3     33  
2                 0             3     33  
3                 0             4     33  
4                 1             4     33

In [6]:
df.corr()

Case Identification    Region  \
Case Identification                            1.000000  0.638407   
Region                                         0.638407  1.000000   
Type of Place of Residence                     0.177207  0.216471   
Source of Drinking Water                      -0.069848 -0.060153   
Type of Toilet Facility                       -0.301690 -0.148401   
Has Electricity                                0.346318  0.289698   
Main Floor Material                           -0.376437 -0.234595   
Main Wall Material                            -0.213831 -0.104933   
Main Roof Material                             0.008252  0.005104   
Has Bicycle                                   -0.146270 -0.126672   
Has Motorcycle or Scooter                     -0.065808 -0.079948   
Has Car or Truck                               0.069636  0.050033   
Has Mosquito Bed Net for Sleeping             -0.209054 -0.076900   
Owns Land Suitable for Agriculture            -0.287512 -0.239653   
Has Bank Account                               0.308240  0.202300   
Wealth Index                                   0.290721  0.261221   
State                                         -0.261572 -0.052171   

                                    Type of Place of Residence  \
Case Identification                                   0.177207   
Region                                                0.216471   
Type of Place of Residence                            1.000000   
Source of Drinking Water                             -0.149851   
Type of Toilet Facility                              -0.252379   
Has Electricity                                       0.451118   
Main Floor Material                                  -0.338956   
Main Wall Material                                   -0.153098   
Main Roof Material                                    0.031477   
Has Bicycle                                          -0.105294   
Has Motorcycle or Scooter                            -0.059524   
Has Car or Truck                                      0.207950   
Has Mosquito Bed Net for Sleeping                    -0.081134   
Owns Land Suitable for Agriculture                   -0.406834   
Has Bank Account                                      0.362684   
Wealth Index                                          0.443147   
State                                                -0.000825   

                                    Source of Drinking Water  \
Case Identification                                -0.069848   
Region                                             -0.060153   
Type of Place of Residence                         -0.149851   
Source of Drinking Water                            1.000000   
Type of Toilet Facility                             0.140699   
Has Electricity                                    -0.139486   
Main Floor Material                                 0.104220   
Main Wall Material                                 -0.000162   
Main Roof Material                                  0.000010   
Has Bicycle                                         0.046862   
Has Motorcycle or Scooter                           0.022469   
Has Car or Truck                                   -0.100930   
Has Mosquito Bed Net for Sleeping                   0.042507   
Owns Land Suitable for Agriculture                  0.143419   
Has Bank Account                                   -0.107729   
Wealth Index                                       -0.092795   
State                                               0.076851   

                                    Type of Toilet Facility  Has Electricity  \
Case Identification                               -0.301690         0.346318   
Region                                            -0.148401         0.289698   
Type of Place of Residence                        -0.252379         0.451118   
Source of Drinking Water                           0.140699        -0.139486   
Type of Toilet Facility                            

In [7]:
num_obs = len(df)
num_true = len(df.loc[df['Has Mosquito Bed Net for Sleeping'] == 1])
num_false = len(df.loc[df['Has Mosquito Bed Net for Sleeping'] == 0])
print("Number of True cases:  {0} ({1:2.2f}%)".format(num_true, (num_true/num_obs) * 100))
print("Number of False cases: {0} ({1:2.2f}%)".format(num_false, (num_false/num_obs) * 100))

Number of True cases:  5431 (70.13%)
Number of False cases: 2313 (29.87%)


In [9]:
#from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split
feature_col_names = ['Region', 'Type of Place of Residence', 'Source of Drinking Water', 'Has Electricity', 'Wealth Index', 'Has Bicycle', 'Has Motorcycle or Scooter', 'Has Car or Truck', 'Owns Land Suitable for Agriculture', 'Has Bank Account', 'Main Floor Material', 'Main Wall Material', 'Main Roof Material']
predicted_class_names = ['Has Mosquito Bed Net for Sleeping']

X = df[feature_col_names].values     # predictor feature columns (8 X m)
y = df[predicted_class_names].values # predicted class (1=true, 0=false) column (1 X m)
split_test_size = 0.20

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=split_test_size, random_state=42) 
                            # test_size = 0.3 is 30%, 42 is the answer to everything

In [10]:
print("{0:0.2f}% in training set".format((len(X_train)/len(df.index)) * 100))
print("{0:0.2f}% in test set".format((len(X_test)/len(df.index)) * 100))

80.00% in training set
20.00% in test set


In [13]:
print("Original True  : {0} ({1:0.2f}%)".format(len(df.loc[df['Has Mosquito Bed Net for Sleeping'] == 1]), (len(df.loc[df['Has Mosquito Bed Net for Sleeping'] == 1])/len(df.index)) * 100.0))
print("Original False : {0} ({1:0.2f}%)".format(len(df.loc[df['Has Mosquito Bed Net for Sleeping'] == 0]), (len(df.loc[df['Has Mosquito Bed Net for Sleeping'] == 0])/len(df.index)) * 100.0))
print("")
print("Training True  : {0} ({1:0.2f}%)".format(len(y_train[y_train[:] == 1]), (len(y_train[y_train[:] == 1])/len(y_train) * 100.0)))
print("Training False : {0} ({1:0.2f}%)".format(len(y_train[y_train[:] == 0]), (len(y_train[y_train[:] == 0])/len(y_train) * 100.0)))
print("")
print("Test True      : {0} ({1:0.2f}%)".format(len(y_test[y_test[:] == 1]), (len(y_test[y_test[:] == 1])/len(y_test) * 100.0)))
print("Test False     : {0} ({1:0.2f}%)".format(len(y_test[y_test[:] == 0]), (len(y_test[y_test[:] == 0])/len(y_test) * 100.0)))


Original True  : 5431 (70.13%)
Original False : 2313 (29.87%)

Training True  : 4362 (70.41%)
Training False : 1833 (29.59%)

Test True      : 1069 (69.01%)
Test False     : 480 (30.99%)


In [ ]:
# Training Initial Algorithm - Using Naive Bayes Machine Learning Model
from sklearn.naive_bayes import GaussianNB

# create Gaussian Naive Bayes model object and train it with the data
nb_model = GaussianNB()

nb_model.fit(X_train, y_train.ravel())

GaussianNB()

In [15]:
# predict values using the training data
nb_predict_train = nb_model.predict(X_train)

# import the performance metrics library
from sklearn import metrics

# Accuracy
print("Accuracy: {0:.4f}".format(metrics.accuracy_score(y_train, nb_predict_train)))
print()

Accuracy: 0.6588



In [16]:
# predict values using the testing data
nb_predict_test = nb_model.predict(X_test)


# training metrics
print("nb_predict_test", nb_predict_test)
print ("y_test", y_test)
print("Accuracy: {0:.4f}".format(metrics.accuracy_score(y_test, nb_predict_test)))


nb_predict_test [1 1 1 ... 1 0 1]
y_test [[1]
 [1]
 [0]
 ...
 [1]
 [1]
 [0]]
Accuracy: 0.6346


In [17]:
print("Confusion Matrix")
print("{0}".format(metrics.confusion_matrix(y_test, nb_predict_test)))
print("")

print("Classification Report")
print(metrics.classification_report(y_test, nb_predict_test))


Confusion Matrix
[[195 285]
 [281 788]]

Classification Report
              precision    recall  f1-score   support

           0       0.41      0.41      0.41       480
           1       0.73      0.74      0.74      1069

    accuracy                           0.63      1549
   macro avg       0.57      0.57      0.57      1549
weighted avg       0.63      0.63      0.63      1549



In [18]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(random_state=42, n_estimators=10)      # Create random forest object
rf_model.fit(X_train, y_train.ravel()) 

RandomForestClassifier(n_estimators=10, random_state=42)

In [19]:
rf_predict_train = rf_model.predict(X_train)
# training metrics
print("Accuracy: {0:.4f}".format(metrics.accuracy_score(y_train, rf_predict_train)))

Accuracy: 0.8920


In [20]:
rf_predict_test = rf_model.predict(X_test)

# training metrics
print("Accuracy: {0:.4f}".format(metrics.accuracy_score(y_test, rf_predict_test)))

Accuracy: 0.6507


In [21]:
print(metrics.confusion_matrix(y_test, rf_predict_test) )
print("")
print("Classification Report")
print(metrics.classification_report(y_test, rf_predict_test))

[[171 309]
 [232 837]]

Classification Report
              precision    recall  f1-score   support

           0       0.42      0.36      0.39       480
           1       0.73      0.78      0.76      1069

    accuracy                           0.65      1549
   macro avg       0.58      0.57      0.57      1549
weighted avg       0.64      0.65      0.64      1549



In [ ]:
#Logistic Regression Model
from sklearn.linear_model import LogisticRegression

lr_model =LogisticRegression(C=0.7, random_state=42, solver='liblinear', max_iter=10000)
lr_model.fit(X_train, y_train.ravel())
lr_predict_test = lr_model.predict(X_test)

# training metrics
print("Accuracy: {0:.4f}".format(metrics.accuracy_score(y_test, lr_predict_test)))
print(metrics.confusion_matrix(y_test, lr_predict_test) )
print("")
print("Classification Report")
print(metrics.classification_report(y_test, lr_predict_test))

Accuracy: 0.6914
[[  15  465]
 [  13 1056]]

Classification Report
              precision    recall  f1-score   support

           0       0.54      0.03      0.06       480
           1       0.69      0.99      0.82      1069

    accuracy                           0.69      1549
   macro avg       0.61      0.51      0.44      1549
weighted avg       0.65      0.69      0.58      1549

